services:
  caesura:
    container_name: caesura
    build: .
    volumes:
    - ./config.yml:/config.yml:ro
    - ./content:/content
    - cache:/cache
    - output:/output

  caddy:
    container_name: caddy
    image: caddy:2-alpine
    ports:
    - "3000:80"
    volumes:
    - caddy_data:/data
    - caddy_config:/config
    - output:/srv
    restart: unless-stopped
    command: caddy file-server --browse --root /srv

volumes:
  output:
  cache:
  caddy_data:
  caddy_config:
