[package]
name = "logging"
version = "0.0.0"
edition = "2021"

[dependencies]
chrono = "^0.4.38"
clap = { version = "^4.5", features = ["derive"] }
colored = "^2.1"
log = { version = "^0.4", features = ["std"] }
serde = { version = "^1.0", features = ["derive"] }
