name: On Push
on:
  push:
env:
  CARGO_TERM_COLOR: always
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - id: cache-samples
      uses: actions/cache@v4
      with:
       path: samples/content
       key: cache-samples

    - if: steps.cache-samples.outputs.cache-hit != 'true'
      run: ./samples/download-sample

    - run: |
        curl "https://github.com/casey/intermodal/releases/download/v0.1.14/imdl-v0.1.14-x86_64-unknown-linux-musl.tar.gz" \
          --location \
          --show-error \
          --silent \
        | tar \
          --extract \
          --gzip \
          --directory "/usr/local/bin" \
          --file - \
          "imdl"

    - run: sudo apt-get update

    - run: sudo apt-get install flac lame sox imagemagick --yes

    - id: release
      env:
        GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: ${{ secrets.RELEASE_SCRIPT }}

    - run: echo "${{ steps.release.outputs.version}}"

    - run: cat "release-notes.md"

    - run: /home/linuxbrew/.linuxbrew/bin/brew install cargo-edit
      if: ${{ steps.release.outputs.version != ''}}

    - run: /home/linuxbrew/.linuxbrew/bin/cargo-set-version set-version ${{ steps.release.outputs.version }}
      if: ${{ steps.release.outputs.version != ''}}

    - run: cargo build --release

    - run: cargo test --release --no-fail-fast
      env:
        API_KEY: ${{ secrets.API_KEY }}
        SOURCE: ${{ secrets.SOURCE }}

    - run: cargo check --quiet --all-targets --message-format short
      continue-on-error: true

    - run: cargo clippy --quiet --all-targets --message-format short
      continue-on-error: true

    - run: cargo fmt --quiet --check
      continue-on-error: true

    - name: gh release create
      if: ${{ steps.release.outputs.version != '' && ! contains(steps.release.outputs.version, '-') }}
      env:
        GH_TOKEN: ${{ github.token }}
      run: >
        gh release create
        "v${{ steps.release.outputs.version }}"
        --title "v${{ steps.release.outputs.version }}"
        --notes-file release-notes.md
        --target ${{ github.ref_name }}

    - name: gh release create --prerelease
      if: ${{ steps.release.outputs.version != '' && contains(steps.release.outputs.version, '-') }}
      env:
        GH_TOKEN: ${{ github.token }}
      run: >
        gh release create
        "v${{ steps.release.outputs.version }}"
        --title "v${{ steps.release.outputs.version }}"
        --notes-file release-notes.md
        --target ${{ github.ref_name }}
        --prerelease

    - name: gh release upload
      run: >
        gh release upload
        "v${{ steps.release.outputs.version }}"
        "target/release/caesura"
        --clobber
        --repo "${{ github.repository }}"
      env:
        GH_TOKEN: ${{ github.token }}
      if: ${{ steps.release.outputs.version != ''}}

    - run: cargo publish --allow-dirty
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      if: ${{ steps.release.outputs.version != ''}}

    - run: echo $GH_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ steps.release.outputs.version != ''}}

    - run: docker build -t caesura .
      if: ${{ steps.release.outputs.version != ''}}

    - run: docker tag caesura ghcr.io/rogueoneecho/caesura:${{ steps.release.outputs.version }}
      if: ${{ steps.release.outputs.version != ''}}

    - run: docker push ghcr.io/rogueoneecho/caesura:${{ steps.release.outputs.version }}
      if: ${{ steps.release.outputs.version != ''}}

    - run: docker tag caesura ghcr.io/rogueoneecho/caesura:latest
      if: ${{ steps.release.outputs.version != '' && ! contains(steps.release.outputs.version, '-') }}

    - run: docker push ghcr.io/rogueoneecho/caesura:latest
      if: ${{ steps.release.outputs.version != '' && ! contains(steps.release.outputs.version, '-') }}
